from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .ast import ConstantDecl, EnumDecl, EnumType, Function, Program, RecordDecl, TypeAliasDecl, TypeName, UnionDecl, ValueType
from .compiler import LoadedCompilation, load_compilation, module_path
from .diagnostics import InscriptionError
from .version import C_HEADER_FORMAT, INTERFACE_JSON_FORMAT
from .semantic import (
    ConstValue,
    TYPE_WIDTHS,
    analyze,
    byte_width,
    constant_table,
    enum_table,
    format_type,
    function_table,
    EnumInfo,
    record_table,
    resolve_value_type,
    resolve_function_table,
    TypeAliasInfo,
    type_alias_table,
    UnionInfo,
    union_table,
    validate_type_aliases,
    validate_union_payloads,
)

HEADER_SUPPORTED_TYPES = {"i32", "u32", "i64", "u64", "f32", "f64"}
C_TYPE_MAP = {
    "i32": "int32_t",
    "u32": "uint32_t",
    "i64": "int64_t",
    "u64": "uint64_t",
    "f32": "float",
    "f64": "double",
}
C_IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


@dataclass(frozen=True)
class InterfaceContext:
    compilation: LoadedCompilation
    type_aliases: dict[str, TypeAliasInfo]
    enums: dict[str, EnumInfo]
    unions: dict[str, UnionInfo]
    records: dict[str, RecordDecl]
    constants: dict[str, ConstValue]
    functions: dict[str, Function]
    root_dir: Path | None


def load_interface_context(source_path: Path, *, module_root: Path | None = None) -> InterfaceContext:
    source_path = source_path.resolve()
    source = source_path.read_text()
    try:
        compilation = load_compilation(source, source_path=source_path, module_root=module_root)
        return make_interface_context(compilation, root_dir=compilation.module_root)
    except InscriptionError as exc:
        raise exc.attach_source(source, source_path) from exc


def make_interface_context(compilation: LoadedCompilation, *, root_dir: Path | None = None) -> InterfaceContext:
    analyze(compilation.program)
    raw_functions = function_table(compilation.program)
    aliases = type_alias_table(compilation.program)
    enums = enum_table(compilation.program)
    unions = union_table(compilation.program)
    records = record_table(compilation.program)
    validate_union_payloads(unions, records)
    validate_type_aliases(records)
    constants = constant_table(compilation.program, records, raw_functions)
    functions = resolve_function_table(raw_functions, records, constants)
    return InterfaceContext(compilation, aliases, enums, unions, records, constants, functions, root_dir)


def emit_interface_json(
    context: InterfaceContext,
    *,
    package_metadata: dict[str, Any] | None = None,
    include_root_module: bool = True,
    root_module: str | None = None,
) -> str:
    compilation = context.compilation
    root_dir = _root_dir(context)
    payload: dict[str, Any] = {
        "format": INTERFACE_JSON_FORMAT,
    }
    if package_metadata is not None:
        payload["package"] = package_metadata
    payload.update(
        {
            "source": _relative_path(compilation.root_path, root_dir),
            "module_root": "." if root_dir is not None else None,
            "root_module": root_module if root_module is not None else compilation.root_program.module_name,
            "modules": [
                *(
                    [
                        _module_json(
                            name=compilation.root_program.module_name,
                            path=compilation.root_path,
                            program=compilation.root_program,
                            context=context,
                        )
                    ]
                    if include_root_module
                    else []
                ),
                *(
                    _module_json(name=module.name, path=module.path, program=module.program, context=context)
                    for module in compilation.modules
                ),
            ],
        }
    )
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def emit_c_header(context: InterfaceContext, *, include_modules: set[str | None] | None = None) -> str:
    prototypes: list[str] = []
    for module_name, program in _ordered_module_programs(context.compilation):
        if include_modules is not None and module_name not in include_modules:
            continue
        for fn in program.functions:
            resolved = context.functions[fn.name]
            if resolved.implementation != "export":
                continue
            prototypes.append(_c_prototype(resolved))

    lines = [
        "/*",
        " * Generated by Inscription.",
        f" * Interface format: {C_HEADER_FORMAT}.",
        " * This header includes exported scalar phrases only.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    lines.extend(prototypes)
    if prototypes:
        lines.append("")
    lines.extend(
        [
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def _module_json(
    *,
    name: str | None,
    path: Path | None,
    program: Program,
    context: InterfaceContext,
) -> dict[str, Any]:
    return {
        "name": name,
        "path": _relative_path(path, _root_dir(context)),
        "documentation": program.documentation,
        "imports": [_import_json(import_decl.module, _root_dir(context)) for import_decl in program.imports],
        "type_aliases": [_type_alias_json(alias, name, context) for alias in program.type_aliases],
        "constants": [_constant_json(const, name, context.constants[const.name], context) for const in program.constants],
        "enums": [_enum_json(enum, context.enums[enum.name], name) for enum in program.enums],
        "unions": [_union_json(union, context.unions[union.name], name) for union in program.unions],
        "records": [
            _record_json(context.records[record.name], name, record.documentation)
            for record in program.records
            if context.records[record.name].layout_kind == "value"
        ],
        "layout_records": [
            _record_json(context.records[record.name], name, record.documentation)
            for record in program.records
            if context.records[record.name].layout_kind != "value"
        ],
        "exports": [
            _function_json(context.functions[fn.name], name)
            for fn in program.functions
            if context.functions[fn.name].implementation == "export"
        ],
        "externs": [
            _function_json(context.functions[fn.name], name)
            for fn in program.functions
            if context.functions[fn.name].implementation == "extern"
        ],
    }


def _import_json(module_name: str, root_dir: Path | None) -> dict[str, Any]:
    path = module_path(root_dir, module_name) if root_dir is not None else None
    return {"module": module_name, "path": _relative_path(path, root_dir), "alias": None}


def _constant_json(decl: ConstantDecl, module_name: str | None, value: ConstValue, context: InterfaceContext) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "name": _display_name(decl.name, module_name),
        "type": _format_interface_type(value.type_name, module_name),
        "documentation": decl.documentation,
        "value": value.value,
    }
    if isinstance(value.type_name, EnumType):
        info = context.enums[value.type_name.name]
        for case_name in info.case_order:
            if info.cases[case_name] == value.value:
                payload["case"] = _display_name(f"{info.name}.{case_name}", module_name)
                break
    return payload


def _type_alias_json(alias: TypeAliasDecl, module_name: str | None, context: InterfaceContext) -> dict[str, Any]:
    target = resolve_value_type(
        alias.target,
        alias.line,
        context.records,
        context.constants,
        context.functions,
        {},
    )
    return {
        "name": _display_name(alias.name, module_name),
        "kind": "type-alias",
        "documentation": alias.documentation,
        "target": _format_interface_type(target, module_name),
    }


def _enum_json(decl: EnumDecl, enum: EnumInfo, module_name: str | None) -> dict[str, Any]:
    return {
        "name": _display_name(enum.name, module_name),
        "kind": "enum",
        "documentation": decl.documentation,
        "underlying_type": enum.underlying_type,
        "cases": [{"name": case_name, "value": enum.cases[case_name]} for case_name in enum.case_order],
    }


def _union_json(decl: UnionDecl, union: UnionInfo, module_name: str | None) -> dict[str, Any]:
    variants = []
    for variant_name in union.variant_order:
        variant = union.variants[variant_name]
        payloads = [
            {
                "name": payload.name,
                "type": _format_interface_type(payload.type_name, module_name),
            }
            for payload in variant.payload_fields
        ]
        variants.append({"name": variant.name, "tag": variant.tag, "payloads": payloads})
    return {
        "name": _display_name(union.name, module_name),
        "kind": "union",
        "documentation": decl.documentation,
        "tag_type": union.tag_type,
        "variants": variants,
    }


def _record_json(record: RecordDecl, module_name: str | None, documentation: str | None) -> dict[str, Any]:
    if record.layout_kind == "value":
        return {
            "name": _display_name(record.name, module_name),
            "kind": "record",
            "documentation": documentation,
            "fields": [
                {"name": field.name, "type": _format_interface_type(field.type_name, module_name)}
                for field in record.fields
            ],
        }

    assert record.layout_info is not None
    kind = "packed-layout-record" if record.layout_kind == "packed" else "layout-record"
    return {
        "name": _display_name(record.name, module_name),
        "kind": kind,
        "documentation": documentation,
        "size": record.layout_info.size,
        "alignment": record.layout_info.alignment,
        "fields": [
            {
                "name": field.name,
                "type": _format_interface_type(field.type_name, module_name),
                "offset": record.layout_info.field_offsets[field.name],
                "size": byte_width(_field_scalar_type(field.type_name)),
                "alignment": _field_alignment(record, _field_scalar_type(field.type_name)),
            }
            for field in record.fields
        ],
        "padding_offsets": list(record.layout_info.padding_offsets),
    }


def _function_json(fn: Function, module_name: str | None) -> dict[str, Any]:
    assert fn.extern_symbol is not None
    return {
        "module": module_name,
        "phrase": fn.display_name,
        "kind": "does" if fn.return_type is None else "gives",
        "symbol": fn.extern_symbol,
        "documentation": fn.documentation,
        "parameters": [
            {"name": param.name, "type": _format_interface_type(param.type_name, module_name)} for param in fn.params
        ],
        "return": None if fn.return_type is None else _format_interface_type(fn.return_type, module_name),
    }


def _c_prototype(fn: Function) -> str:
    assert fn.extern_symbol is not None
    symbol = fn.extern_symbol
    if C_IDENTIFIER_RE.fullmatch(symbol) is None:
        raise InscriptionError(f"C header emission requires exported symbol {symbol} to be a C identifier", fn.line)
    return_type = "void" if fn.return_type is None else _c_type(fn.return_type, symbol, fn.line)
    if not fn.params:
        args = "void"
    else:
        args = ", ".join(f"{_c_type(param.type_name, symbol, fn.line)} arg{index}" for index, param in enumerate(fn.params))
    prototype = f"{return_type} {symbol}({args});"
    if fn.documentation is None:
        return prototype
    return "\n".join((*_c_documentation_comment(fn.documentation), prototype))


def _c_documentation_comment(documentation: str) -> tuple[str, ...]:
    lines = ["/*"]
    for doc_line in documentation.splitlines() or [""]:
        lines.append(f" * {doc_line.replace('*/', '* /')}")
    lines.append(" */")
    return tuple(lines)


def _c_type(type_name: ValueType, symbol: str, line: int) -> str:
    if not isinstance(type_name, str) or type_name not in HEADER_SUPPORTED_TYPES:
        raise InscriptionError(
            "C header emission supports exported scalar types i32, u32, i64, u64, f32, and f64 in v0.21; "
            f"{symbol} uses {format_type(type_name)}",
            line,
        )
    return C_TYPE_MAP[type_name]


def _ordered_module_programs(compilation: LoadedCompilation) -> tuple[tuple[str | None, Program], ...]:
    return ((compilation.root_program.module_name, compilation.root_program),) + tuple(
        (module.name, module.program) for module in compilation.modules
    )


def _field_scalar_type(type_name: ValueType) -> TypeName:
    if isinstance(type_name, EnumType):
        return type_name.underlying_type
    assert isinstance(type_name, str)
    return type_name


def _field_alignment(record: RecordDecl, type_name: TypeName) -> int:
    return 1 if record.layout_kind == "packed" else TYPE_WIDTHS[type_name] // 8


def _format_interface_type(type_name: ValueType, module_name: str | None) -> str:
    text = format_type(type_name)
    if module_name is not None:
        text = text.replace(f"{module_name}.", "")
    return text


def _display_name(name: str, module_name: str | None) -> str:
    if module_name is not None and name.startswith(f"{module_name}."):
        return name[len(module_name) + 1 :]
    return name


def _root_dir(context: InterfaceContext) -> Path | None:
    if context.root_dir is not None:
        return context.root_dir
    if context.compilation.root_path is not None:
        return context.compilation.root_path.parent
    return None


def _relative_path(path: Path | None, root_dir: Path | None) -> str | None:
    if path is None:
        return None
    resolved = path.resolve()
    if root_dir is not None:
        try:
            return resolved.relative_to(root_dir.resolve()).as_posix()
        except ValueError:
            pass
    return path.name
